import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const snap=p=>p.evaluate(()=>globalThis.__W9_BALL_TEST__?.snapshot());
test('two seeded macro worlds differ and retain physical continuous 3D roadway',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w104&coaster=extreme&seed=17&start=macro&world=5');
 await expect.poll(async()=>!!(await snap(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 let s=await snap(page);
 expect(s.trilogy.macroMode).toBe(true);expect(s.trilogy.worldIndex).toBe(5);
 expect(s.trilogy.active.alignedSurface).toBe(true);
 expect(s.trilogy.active.guardBodies).toBeGreaterThan(150);
 expect(s.trilogy.macroMotifs.length).toBeGreaterThanOrEqual(3);
 const a=s.trilogy.macroSignature;
 await page.locator('#start').click();await page.waitForTimeout(500);
 s=await snap(page);expect(s.trilogy.touchDrive.boosts).toBe(0);
 await page.mouse.move(190,680);await page.mouse.down();
 await page.mouse.move(190,510,{steps:10});await page.waitForTimeout(620);
 s=await snap(page);
 expect(s.trilogy.touchDrive.boosts).toBe(1);
 expect(s.trilogy.nativeCcdConfigured).toBe(true);
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(errors).toEqual([]);
 await page.mouse.up();
 await page.screenshot({path:'test-results/w104-macro-world5.png'});
 await page.goto('/ball/?mode=endless&edition=w104&coaster=extreme&seed=17&start=macro&world=6');
 await expect.poll(async()=>!!(await snap(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 s=await snap(page);
 expect(s.trilogy.worldIndex).toBe(6);
 expect(s.trilogy.macroSignature).not.toBe(a);
 expect(s.trilogy.macroKind).not.toBe('');
 expect(errors).toEqual([]);
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w104-macro-evidence.json',JSON.stringify({s,errors},null,2));
});
test('actual magnetic tube transfers momentum into next world, never resets to zero',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w104&coaster=extreme&seed=17&start=spiral&probe=tube');
 await expect.poll(async()=>!!(await snap(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 await page.locator('#start').click();
 await expect.poll(async()=>(await snap(page))?.trilogy?.worldIndex,
  {timeout:110000,intervals:[650]}).toBe(5);
 let s=await snap(page);
 expect(s.trilogy.exitBoostCount).toBe(1);
 expect(s.trilogy.lastExitSpeed).toBeGreaterThanOrEqual(72);
 expect(s.trilogy.macroKind.length).toBeGreaterThan(4);
 expect(s.trilogy.active.alignedSurface).toBe(true);
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(errors).toEqual([]);
 await page.screenshot({path:'test-results/w104-magnetic-exit.png'});
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w104-handoff-evidence.json',JSON.stringify({s,errors},null,2));
});
