import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const snap=p=>p.evaluate(()=>globalThis.__W9_BALL_TEST__?.snapshot());
const speed=s=>Math.hypot(...s.linearVelocity);
test('World4 starts stationary; repeated swipe accelerates, held touch steers; camera tracks ball',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w101&coaster=extreme&seed=17&start=spiral');
 await expect.poll(async()=>!!(await snap(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 let s=await snap(page);
 expect(s.trilogy.worldIndex).toBe(4);
 expect(s.trilogy.touchDriveMode).toBe(true);
 expect(s.trilogy.active.stableRoad).toBe(true);
 expect(s.trilogy.active.roadBodies).toBeGreaterThan(500);
 await page.locator('#start').click();
 await page.waitForTimeout(2500);
 s=await snap(page);
 expect(s.phase).toBe('running');
 expect(s.trilogy.touchDrive.boosts).toBe(0);
 expect(s.trilogy.spiralInputFrames).toBe(0);
 expect(speed(s)).toBeLessThan(3.5);
 expect(s.trilogy.falls).toBe(0);
 await page.mouse.move(195,700);await page.mouse.down();
 await page.mouse.move(195,570,{steps:10});
 await page.waitForTimeout(950);
 s=await snap(page);
 expect(s.trilogy.touchDrive.holding).toBe(true);
 expect(s.trilogy.touchDrive.boosts).toBe(1);
 expect(s.trilogy.spiralInputFrames).toBeGreaterThan(20);
 expect(speed(s)).toBeGreaterThan(6);
 await page.mouse.move(265,575,{steps:10});
 await page.waitForTimeout(400);
 s=await snap(page);
 expect(s.trilogy.touchDrive.steer).toBeGreaterThan(.5);
 expect(s.trilogy.touchDrive.forward).toBeGreaterThan(.5);
 await page.mouse.up();
 await page.waitForTimeout(400);
 s=await snap(page);
 expect(s.trilogy.touchDrive.active).toBe(false);
 expect(s.trilogy.touchDrive.forward).toBe(0);
 const oldBoosts=s.trilogy.touchDrive.boosts;
 await page.mouse.move(195,700);await page.mouse.down();
 await page.mouse.move(190,565,{steps:10});
 await page.waitForTimeout(280);
 s=await snap(page);
 expect(s.trilogy.touchDrive.boosts).toBe(oldBoosts+1);
 expect(s.trilogy.falls).toBeLessThan(3);
 expect(s.trilogy.spiralMode).toBe(true);
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(s.trilogy.worldIndex).toBe(4);
 expect(errors).toEqual([]);
 await page.mouse.up();
 await page.screenshot({path:'test-results/w101-touch-drive.png'});
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w101-browser-evidence.json',JSON.stringify({s,errors},null,2));
});
