import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const state=page=>page.evaluate(()=>globalThis.__W9_BALL_TEST__?.snapshot());
const speed=s=>Math.hypot(...s.linearVelocity);
test('W10.2 CCD: stationary -> fast swipe -> hold -> repeated boost while camera remains finite',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w102&coaster=extreme&seed=17&start=spiral');
 await expect.poll(async()=>(await state(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 await page.locator('#start').click();await page.waitForTimeout(1400);
 let s=await state(page);
 expect(s.trilogy.stabilizedMode).toBe(true);
 expect(s.trilogy.active.stableRoad).toBe(true);
 expect(s.trilogy.touchDrive.boosts).toBe(0);
 expect(speed(s)).toBeLessThan(4);
 await page.mouse.move(195,680);await page.mouse.down();
 await page.mouse.move(195,510,{steps:12});
 await page.waitForTimeout(950);
 s=await state(page);
 expect(s.trilogy.nativeCcdConfigured).toBe(true);
 expect(s.trilogy.ccdRefreshes).toBeGreaterThanOrEqual(1);
 expect(s.trilogy.touchDrive.boosts).toBe(1);
 expect(speed(s)).toBeGreaterThan(10);
 const moving=speed(s);
 await page.mouse.up();await page.waitForTimeout(280);
 await page.mouse.move(195,670);await page.mouse.down();
 await page.mouse.move(195,520,{steps:12});
 await page.waitForTimeout(550);
 s=await state(page);
 expect(s.trilogy.touchDrive.boosts).toBe(2);
 expect(speed(s)).toBeGreaterThan(Math.min(14,moving-1));
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(s.trilogy.falls).toBeLessThan(3);
 expect(errors).toEqual([]);
 await page.mouse.up();
 await page.screenshot({path:'test-results/w102-fast-ccd.png'});
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w102-speed-evidence.json',JSON.stringify({s,errors},null,2));
});
test('W10.2 physical helix guard triggers contact boost, green glow and pooled sparks',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w102&coaster=extreme&seed=17&start=spiral&probe=guard');
 await expect.poll(async()=>(await state(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 await page.locator('#start').click();
 await page.mouse.move(135,690);await page.mouse.down();
 await page.mouse.move(185,530,{steps:10});
 await expect.poll(async()=>(await state(page))?.trilogy.guardContactCount,
  {timeout:12000,intervals:[250]}).toBeGreaterThan(0);
 await expect.poll(async()=>(await state(page))?.trilogy.guardBoostFrames,
  {timeout:12000,intervals:[250]}).toBeGreaterThan(0);
 await page.waitForTimeout(330);
 const s=await state(page);
 expect(s.trilogy.guardSparkFrames).toBeGreaterThan(0);
 expect(s.trilogy.active.guardBodies).toBeGreaterThan(100);
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(errors).toEqual([]);
 await page.screenshot({path:'test-results/w102-real-rail-contact.png'});
 await page.mouse.up();
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w102-contact-evidence.json',JSON.stringify({s,errors},null,2));
});
