import {test,expect} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
const read=page=>page.evaluate(()=>globalThis.__W9_BALL_TEST__?.snapshot());
test('extreme rollercoaster enters World 4 with real generated guard/grind physics and higher speed',async({page})=>{
 test.setTimeout(360000);
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w97&coaster=extreme&seed=17');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 let state=await read(page);
 expect(state.trilogy.extremeCoasters).toBe(true);
 expect(state.trilogy.richMode).toBe(true);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.trilogy.worldIndex,{timeout:280000,intervals:[300]}).toBe(4);
 await expect.poll(async()=>(await read(page))?.trilogy.worldContacts[3],{timeout:22000}).toBeGreaterThan(0);
 state=await read(page);
 expect(state.phase).toBe('running');
 expect(state.trilogy.retired[1].guardBodies).toBeGreaterThan(20);
 expect(state.trilogy.retired[1].grindTops).toBeGreaterThan(15);
 expect(state.trilogy.retired[2].guardBodies).toBeGreaterThan(20);
 expect(state.trilogy.retired[2].grindTops).toBeGreaterThan(15);
 expect(state.trilogy.active.guardBodies).toBeGreaterThan(20);
 expect(state.trilogy.active.grindTops).toBeGreaterThan(15);
 expect(state.trilogy.active.grindSides).toBeGreaterThan(20);
 expect(state.trilogy.activeWorldRoots).toBe(1);
 expect(state.trilogy.entries).toBe(3);
 expect(state.trilogy.exits).toBe(3);
 expect(state.trilogy.generatedMaxSpeed).toBeGreaterThan(36);
 expect(state.trilogy.cameraFinite).toBe(true);
 expect(state.trilogy.maxRadiusError).toBeLessThan(.002);
 expect(state.trilogy.journeys.every(j=>j.validation.valid)).toBe(true);
 expect(state.trilogy.retired.every(w=>w.disposed&&w.liveBodies===0)).toBe(true);
 expect(errors).toEqual([]);
 await page.screenshot({path:'test-results/w97-generated-world.png'});
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w97-browser-evidence.json',JSON.stringify({state,errors},null,2));
});
