import {test,expect} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
const read=page=>page.evaluate(()=>globalThis.__W9_BALL_TEST__?.snapshot());

test('minimalist long coiled 3D world streams from faded magnetic tube, then drives into World 5',async({page})=>{
 test.setTimeout(420000);
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/ball/?mode=endless&edition=w98&coaster=extreme&seed=17');
 await expect.poll(async()=>(await read(page))?.physicsLoaded,{timeout:30000}).toBe(true);
 let s=await read(page);
 expect(s.trilogy.trackFirstMode).toBe(true);
 expect(s.trilogy.active.islands).toBe(0);
 expect(s.trilogy.active.minimalist).toBe(true);
 await page.locator('#start').click();
 await expect.poll(async()=>(await read(page))?.trilogy.themeFade,{timeout:130000,intervals:[200]}).toBeGreaterThan(.5);
 await expect.poll(async()=>(await read(page))?.trilogy.worldIndex,{timeout:270000,intervals:[300]}).toBe(4);
 s=await read(page);
 expect(s.phase).toBe('running');
 expect(s.trilogy.active.islands).toBe(0);
 expect(s.trilogy.active.minimalist).toBe(true);
 expect(s.trilogy.active.maxElevation).toBeGreaterThan(23);
 expect(s.trilogy.active.boxObstacles).toBeGreaterThan(11);
 expect(s.trilogy.active.roadBodies).toBeGreaterThan(200);
 expect(s.trilogy.active.guardBodies).toBeGreaterThan(15);
 expect(s.trilogy.active.grindTops).toBeGreaterThan(15);
 expect(s.trilogy.entries).toBe(3);
 expect(s.trilogy.exits).toBe(3);
 expect(s.trilogy.retired.every(w=>w.islands===0&&w.disposed&&w.liveBodies===0)).toBe(true);
 await page.screenshot({path:'test-results/w98-world4-track-only.png'});
 await expect.poll(async()=>(await read(page))?.trilogy.worldIndex,{timeout:190000,intervals:[400]}).toBe(5);
 s=await read(page);
 expect(s.phase).toBe('running');
 expect(s.trilogy.falls).toBeLessThan(3);
 expect(s.trilogy.active.islands).toBe(0);
 expect(s.trilogy.journeys.every(j=>j.validation.valid)).toBe(true);
 expect(s.trilogy.cameraFinite).toBe(true);
 expect(s.trilogy.maxRadiusError).toBeLessThan(.002);
 expect(errors).toEqual([]);
 await mkdir('test-results',{recursive:true});
 await writeFile('test-results/w98-five-world-evidence.json',JSON.stringify({s,errors},null,2));
});
