import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const base=process.env.W9_3_BASE_SHA;
if(!base)throw new Error('Missing accepted W9.3 base');
const files=execFileSync('git',['diff','--name-only',base+'...HEAD'],{encoding:'utf8'}).trim().split(/\r?\n/u).filter(Boolean);
const forbidden=files.filter(f=>f.startsWith('src/')||f.startsWith('engine/')||f.startsWith('core/')||f==='package.json'||f==='spikes/w9-playcanvas/asset-manifest.json');
const root='playtest-dist/3d';
const js=fs.readdirSync(root+'/assets').filter(f=>f.endsWith('.js'));
const sizes=js.map(f=>({file:f,bytes:fs.statSync(root+'/assets/'+f).size}));
const failures=[];
if(forbidden.length)failures.push('Frozen gameplay or shared code churn: '+forbidden.join(', '));
if(!files.includes('spikes/w9-playcanvas/src/SoftAvatar.ts'))failures.push('No dedicated smooth avatar implementation');
if(!fs.existsSync('evidence/w9-3/W9.3-1-portrait-390x844-running.png'))failures.push('Missing real portrait screenshot');
if(!fs.existsSync('evidence/w9-3/W9.3-1-landscape-844x390-running.png'))failures.push('Missing landscape screenshot');
if(!fs.existsSync('evidence/w9-3/W9.3-1-small-android-360x800-running.png'))failures.push('Missing small Android screenshot');
const art=fs.readFileSync('spikes/w9-playcanvas/src/SoftAvatar.ts','utf8');
if(!art.includes("type: 'sphere'")||art.includes("type: 'box'"))failures.push('Avatar mesh must be rounded, no box geometry');
const manifest={marker:failures.length?'W9_3_1_ROUNDED_AVATAR_TECHNICAL_FAIL':'W9_3_1_ROUNDED_AVATAR_CONTRACT_PASS',base,modified:files,bundles:sizes,failures};
fs.mkdirSync('evidence/w9-3',{recursive:true});
fs.writeFileSync('evidence/w9-3/contract.json',JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify(manifest,null,2));
if(failures.length)throw new Error(failures.join('; '));
console.log(manifest.marker);
